<?php

/**
 * @package Demo
 * @author Iurii Makukh <gplcart.software@gmail.com>
 * @copyright Copyright (c) 2015, Iurii Makukh
 * @license https://www.gnu.org/licenses/gpl.html GNU/GPLv3
 */
return array(
    array(
        'price' => 115.99,
        'sku' => 'EF527D-1AV',
        'title' => 'Casio Men\'s Edifice Stainless Steel Multi-Function Watch',
        'description' => 'The Casio Men\'s Edifice Stainless Steel Multi-Function Chronograph Watch exists at the crossroads of comfort, style and functionality which is where you should be. This dynamic timepiece kicks off with a 45.5mm stainless steel case and a stationary bezel with a textured edge. There are also pushers on both sides of the case, along with a protected screw-down crown on the right side. The watch\'s black dial is a flurry of function with a sliding inner bezel, silver-toned hour markers and hands, which are powered by quartz movement. The dial also features three chronograph sub-dials with 12-hour, 60-minute and 60-second displays, along with a date display window at the 3 \'o clock position. The stainless steel three-link bracelet straps this watch to the wrist, while a fold-over push-button clasp with a safety ensures that it stays there. Finally, this watch offers water resistance up to 330 feet (100 meters).',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Casio'],
    ),
    array(
        'price' => 166,
        'sku' => 'EQS500DB-1A1',
        'title' => 'Casio Men\'s Edifice Tough Solar Stainless Steel Multi-Function Watch with Link Bracelet',
        'description' => 'This Self-Charging Edifice model eliminates the need for battery changes through its unique Solar Powered system. Robust enough to power functions, such as its 1/100th Chronograph, 29-City World Time and Daily Alarm, the EQS500DB-1A1 is not only intelligent, itΓÇÖs tough also. The solid stainless steel case with mineral glass is water resistant up to 100 meters. From Casio, a towering edifice in the watch world comes the Casio Men\'s Edifice Stainless Steel Multi-Function Chronograph Watch. It kicks off with a 45.8mm stainless steel case with a black-toned stainless steel stationary bezel. The crown and pushers grace both sides of the stainless steel case. These elements cradle a black dial that is a flurry of function protected by a mineral crystal. The dial features silver-toned luminous hour markers and hands powered by precise quartz movement. The dial also features chronograph sub-dials with 1/100-second, day, 60-second and 24-hour displays. A three-link stainless steel bracelet straps this watch to the wrist, while a fold-over push-button safety clasp makes sure it stays there. This watch also features solar power, a full auto calendar and water resistance up to 330 feet (100 meters). Note:If the watch is in any mode other then timekeeping the second hand will not spin (unless chronograph is actually running) The way to find out what mode you are in please check the sub-dial located at the 3:00 position if it is not pointing to the day of the week then the watch is not in timekeeping mode thus the second hand will not spin.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Casio'],
    ),
    array(
        'price' => 68.49,
        'sku' => 'SGW500H-2BV',
        'title' => 'Casio Men\'s Resin Analog Digital Twin Sensor Multi-Function Watch',
        'description' => 'This new Twin Sensor model features temperature and direction sensors in a large easy-to-read analog-digital format, in addition to a large case with easy-to-press buttons. Direction readings are displayed within the digital window, while the second hand acts as a compass needle to indicate magnetic north. The watch also features sunrise/sunset data so you can know how much longer to hike or how much light you might have left to capture some great photography on your next adventure.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Casio'],
    ),
    array(
        'price' => 160,
        'sku' => 'AW1510-54L',
        'title' => 'Citizen Men\'s AW1510-54L Drive - WDR Collection Blue Dial Silvertone Stainless Steel Watch',
        'description' => 'This watch features a brilliant blue dial adorned with large grey Arabic numerals and markers. A day window provides convenient reference while the whole piece gently rests on the wrist with a comfortable stainless steel bracelet. The silvertone piece is water resistant up to 100 meters.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Citizen'],
    ),
    array(
        'price' => 146,
        'sku' => 'AW1361-10H',
        'title' => 'Citizen Men\'s Eco-Drive Avion Watch',
        'description' => 'Avion is a vintage-inspired timepiece reminiscent of transatlantic flights from the 1950\'s. Design cues taken from the golden age of travel include the rich brown leather strap with contrast stitching, oversized luminous numbers and classic day/date function. In a stainless steel case with charcoal grey dial.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Citizen'],
    ),
    array(
        'price' => 520,
        'sku' => 'JY0000-53E',
        'title' => 'Citizen Men\'s Eco-Drive Skyhawk AT Watch',
        'description' => 'Redefine atomic timekeeping with radio-controlled accuracy in 4 zones combined with Eco-Drive technology. World time in 43 cities, 1/100 second chrono up to 24 hours, perpetual calendar, 99-minute countdown timer, power reserve & 2 alarms. Includes GMT, rotating slide rule bezel, non-reflective crystal. Stainless steel with black ion plated bezel.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Citizen'],
    ),
    array(
        'price' => 140,
        'sku' => 'EP5914-07A',
        'title' => 'Citizen Women\'s Eco-Drive Straps Watch',
        'description' => 'A watch for every day and every occasion. A stylish appearance dressed up or dressed down. In stainless steel with a dark brown leather strap. Gold accents on the crown, index and hands complete the look.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Citizen'],
    ),
    array(
        'price' => 200,
        'sku' => 'EW2294-53L',
        'title' => 'Citizen Women\'s Eco-Drive Corso Watch',
        'description' => 'Sporty yet elegant, Corso allows you to stand out from the crowd with its contemporary 3-hand look with date and water resistance to 100 meters. Also featuring a sporty deep blue dial on a two-tone stainless steel case and bracelet.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Citizen'],
    ),
    array(
        'price' => 260,
        'sku' => 'FE1154-57A',
        'title' => 'Citizen Women\'s Silhouette Crystal Watch',
        'description' => 'Freshen up your watch collection this season ladies with the new Citizen Silhouette Crystal. Fashion forward and ready to be shown off with a unique decorated dial with Swarovski crystals. Shown here in a two-tone stainless steel case and bracelet with silver dial featuring date.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Citizen'],
    ),
    array(
        'price' => 1499,
        'sku' => 'T0356143605100',
        'title' => 'Tissot Men\'s Couturier Valjoux Automatic Chronograph Black Leather Watch',
        'description' => 'This men\'s watch from the Couturier Valjoux collection features a black leather strap and black automatic chronograph dial',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Tissot'],
    ),
    array(
        'price' => 577.49,
        'sku' => 'T41118335',
        'title' => 'Tissot Women\'s Le Locle Automatic Stainless Steel Watch',
        'description' => 'This women\'s watch from the Le Locle Double Happiness collection features a stainless steel bracelet and white automatic dial.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Tissot'],
    ),
    array(
        'price' => 289.49,
        'sku' => 'T0842101601704',
        'title' => 'Tissot Women\'s T-Trend Pinky Brown Leather Watch',
        'description' => 'This women\'s watch from the T-Trend Pinky collection features a brown leather strap and silver dial.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Tissot'],
    ),
    array(
        'price' => 1740,
        'sku' => 'T0373091103701',
        'title' => 'Tissot Women\'s My-T Crystal Watch',
        'description' => 'Fluid Elegance. This Tissot My-T watch comes with a case set in motion by T-shaped elements attaching it to the bracelet. Genuine diamonds sparkle on the stainless steel bezel.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 3,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Tissot'],
    ),
    array(
        'price' => 1740,
        'sku' => 'T49851',
        'title' => 'Timex Men\'s Expedition Rugged Digital Vibration Alarm Watch',
        'description' => 'A vibrating alarm function, 100-hour chronograph and three time zone settings are featured on this digital watch from Timex. An Indiglo night light, black dial and resin strap finish this unique Expedition timepiece.  The watch is water resistant up to a depth of 100 meters or 330 feet. This makes it ideal for swimmers and those actively involved in outdoor activities during inclement weather. It features an auto-repeat alarm system with three different alert types: vibration, sound, or both. Other useful features include a timer and a stopwatch in situations where timing is critical.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 136,
        'sku' => 'T2N720DH',
        'title' => 'Timex Men\'s Intelligent Quartz Tide-Temp-Compass Watch',
        'description' => 'With multiple functions including a tide tracker, temperature sensor and electronic compass all driven by a dedicated fourth hand the Timex┬« Tide-Temp-Compass is the ultimate accessory for the tech savvy professional with a love for adventure.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 6,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 34,
        'sku' => 'T45181',
        'title' => 'Timex Men\'s Expedition Analog-Digital Nylon Strap Watch',
        'description' => 'A classic analog style with easy-to-read digital display is featured on this men\'s watch from Timex. A durable and lightweight olive green resin case comes and a brown nylon performance strap complete this rugged timepiece. Keep track of time on camping or hiking trips with this durable watch by Timex. Luminescent hands on the watch\'s face let you tell time in the dark, and the tang buckle keeps the nylon strap secure on your wrist for comfortable all-day wear. Water resistant to 330 feet, this watch can be worn with confidence in virtually any outdoor setting.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 10,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 70,
        'sku' => 'TW4B044009J',
        'title' => 'Timex Men\'s Expedition Scout Chrono Tan Leather Slip-Thru Strap Watch',
        'description' => 'This time-honored best-seller just got a little better. We\'ve upgraded our ulitarian field watch with a 30-minute chronograph, a well built oversized case, and of course, our signature arrow second hand.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 3,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 35,
        'sku' => 'T2N065',
        'title' => 'Timex Men\'s Elevated Classics Dress Brown Leather Strap Watch',
        'description' => 'A brown leather strap with crocodile texture adds a dressy touch to the classic styling of this men\'s watch from Timex. The white dial is easy to read and is surrounded by a goldtone case. The simple, sophisticated look of this watch pairs well with your classic style, and the accuracy of the quartz movement keeps you on time. The large watch face makes it easy to see the time even with a quick surreptitious glance during a long meeting, and the Timex backlight feature lets you sneak a look during a long movie.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Men\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 35,
        'sku' => 'TW2P688009J',
        'title' => 'Timex Women\'s Easy Reader Honey Brown Crocodile Leather Strap Watch',
        'description' => 'Offering simplicity and sophistication, this stylish and functional women\'s Timex watch is crafted with a round silvertone case and a honey-brown crocodile leather strap. A clean, off-white dial houses black hands and classic black Arabic numeral hour markers.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 7,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 35,
        'sku' => 'TW5K893009J',
        'title' => 'Timex Women\'s Ironman Classic 30 Blue/Silver-Tone/Black Watch',
        'description' => 'This updated case honors our original 1986 design, but we promise the technology is as forward-thinking as ever.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 99,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 35,
        'sku' => 'T5K8099J',
        'title' => 'Timex Women\'s Ironman Rugged Black/ Lime Watch',
        'description' => 'A wide digital display adds convenience to this modern black watch from Timex. A comfortable resin strap and lime accents complete this timepiece.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 10,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 35,
        'sku' => 'T2N8699J',
        'title' => 'Timex Women\'s Weekender Slip-thru Black Nylon Strap Watch',
        'description' => 'This lovely women\'s Weekender slip-thru watch from Timex features a polished chrome brass case with a coordinating black nylon strap. The black dial sets the stage for grey hands and Arabic numerals for easy time-telling.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 55,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 35,
        'sku' => 'T2M570',
        'title' => 'Timex Women\'s Cavatina Stainless Steel Expansion Band Watch',
        'description' => 'Black Arabic numeral hour markers stand out against a silver dial in this fine women\'s watch from Timex. The Core Cavatina timepiece offers two-tone brass case and expansion bracelet with easy slip-on styling.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
    array(
        'price' => 45,
        'sku' => 'T257719J',
        'title' => 'Timex Women\'s Elevated Classics Dress Two-tone Steel Bracelet Watch',
        'description' => 'Classically styled and updated with the latest Timex timekeeping technology, the two-tone Timex Women\'s Sport Chic stainless steel watch makes a great accent to both your everyday and business wear. It features a round watch case with a gold-tone bezel that frames a white dial background with black Arabic numerals and gold hands (with seconds hand). The stainless steel bracelet band features trident shaped links in gold and silver tones, and it\'s joined by a push button fold over clasp. This watch also features a 10-year battery life, water resistance to 165 feet (50 meters), and a date display at 3 o\'clock. With the Quick Date function, you can set the date on the watch without turning the crown for every 24-hour period. Just pull the stem halfway out, and turn until desired date is reached.',
        'store_id' => $this->store_id,
        'user_id' => $this->user_id,
        'stock' => 1,
        'currency' => 'USD',
        'category_id' => $this->created['category']['Women\'s Watches'],
        'brand_category_id' => $this->created['category']['Timex'],
    ),
);
